module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      background: "#DFF0D8",
      foreground: "#397901",
      decoration: "#273385",
    },
    screens: {
      sphone: { max: "640px" },
      phone: { max: "768px" },
      tablet: { min: "769px", max: "900px" },
      desktop: { min: "901px" },
    },
    extend: {},
  },
  plugins: [],
  safelist: [
    "blur-none",
    "blur-sm",
    "blur",
    "blur-md",
    "blur-lg",
    "blur-xl",
    "blur-2xl",
    "blur-3xl",
    "brightness-0",
    "brightness-50",
    "brightness-75",
    "brightness-100",
    "brightness-105",
    "brightness-110",
    "brightness-125",
    "brightness-150",
    "brightness-200",
    "p-0",
    "p-5",
    "p-10",
    "p-20",
    "gap-0",
    "gap-10",
    "gap-16",
    "gap-20",
    "gap-24",
    "gap-28",
    "gap-32",
    "gap-40",
    "gap-52",
    "gap-x-0",
    "gap-x-10",
    "gap-x-16",
    "gap-x-20",
    "gap-x-24",
    "gap-x-28",
    "gap-x-32",
    "gap-x-40",
    "gap-x-52",
    "gap-y-0",
    "gap-y-10",
    "gap-y-16",
    "gap-y-20",
    "gap-y-24",
    "gap-y-28",
    "gap-y-32",
    "gap-y-40",
    "gap-y-52",
    "order-none",
    "order-first",
    "order-last",
    "order-1",
    "order-2",
    "order-3",
    "order-4",
    "phone:order-1",
    "phone:order-2",
    "phone:order-3",
    "phone:order-4",
    "w-1/4",
    "w-2/4",
    "w-3/4",
    "w-full",
    "text-left",
    "text-center",
    "text-right",
  ],
};
